<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="8" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="86504" started-at="2019-04-03T07:45:33Z" finished-at="2019-04-03T07:46:59Z">
    <groups>
    </groups>
    <test name="My test" duration-ms="86504" started-at="2019-04-03T07:45:33Z" finished-at="2019-04-03T07:46:59Z">
      <class name="testcases.EnterCItyName_Testcases">
        <test-method status="FAIL" signature="Login_process(java.lang.String)[pri:0, instance:testcases.EnterCItyName_Testcases@cb5822]" name="Login_process" duration-ms="12599" started-at="2019-04-03T13:15:55Z" data-provider="checking_property" finished-at="2019-04-03T13:16:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[aberdeen]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 1 expected [4] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 2 expected [7] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [8] but found [5],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [6],
	Verifying the maximum pressure for the day 4 expected [1011] but found [1006]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 1 expected [4] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 2 expected [7] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [8] but found [5],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [6],
	Verifying the maximum pressure for the day 4 expected [1011] but found [1006]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_process -->
        <test-method status="FAIL" signature="Login_process(java.lang.String)[pri:0, instance:testcases.EnterCItyName_Testcases@cb5822]" name="Login_process" duration-ms="10098" started-at="2019-04-03T13:16:08Z" data-provider="checking_property" finished-at="2019-04-03T13:16:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dundee]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [7] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [7],
	Verifying the maximum pressure for the day 4 expected [1019] but found [1014]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [7] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [7],
	Verifying the maximum pressure for the day 4 expected [1019] but found [1014]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_process -->
        <test-method status="FAIL" signature="Login_process(java.lang.String)[pri:0, instance:testcases.EnterCItyName_Testcases@cb5822]" name="Login_process" duration-ms="8817" started-at="2019-04-03T13:16:18Z" data-provider="checking_property" finished-at="2019-04-03T13:16:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[edinburgh]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [8] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [6],
	Verifying the maximum pressure for the day 4 expected [1005] but found [999],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [11] but found [10]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [8] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [9] but found [6],
	Verifying the maximum pressure for the day 4 expected [1005] but found [999],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [11] but found [10]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_process -->
        <test-method status="FAIL" signature="Login_process(java.lang.String)[pri:0, instance:testcases.EnterCItyName_Testcases@cb5822]" name="Login_process" duration-ms="10817" started-at="2019-04-03T13:16:27Z" data-provider="checking_property" finished-at="2019-04-03T13:16:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[glasgow]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [6] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [10] but found [6],
	Verifying the maximum pressure for the day 4 expected [1011] but found [1006],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [11] but found [10]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [6] but found [3],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [10] but found [6],
	Verifying the maximum pressure for the day 4 expected [1011] but found [1006],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [11] but found [10]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_process -->
        <test-method status="FAIL" signature="Login_process(java.lang.String)[pri:0, instance:testcases.EnterCItyName_Testcases@cb5822]" name="Login_process" duration-ms="12036" started-at="2019-04-03T13:16:37Z" data-provider="checking_property" finished-at="2019-04-03T13:16:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[perth]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [4] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [8] but found [5],
	Verifying the maximum pressure for the day 4 expected [1005] but found [999],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [9] but found [8]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [4] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [5] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [8] but found [5],
	Verifying the maximum pressure for the day 4 expected [1005] but found [999],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [9] but found [8]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_process -->
        <test-method status="FAIL" signature="Login_process(java.lang.String)[pri:0, instance:testcases.EnterCItyName_Testcases@cb5822]" name="Login_process" duration-ms="9922" started-at="2019-04-03T13:16:50Z" data-provider="checking_property" finished-at="2019-04-03T13:16:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[stirling]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [3] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [4] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [6] but found [4],
	Verifying the maximum pressure for the day 4 expected [987] but found [982],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [7] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying the maximum wind speed displayed in ui for the day 2 expected [3] but found [1],
	Verifying the maximum wind speed displayed in ui for the day 3 expected [4] but found [2],
	Verifying the maximum wind speed displayed in ui for the day 4 expected [6] but found [4],
	Verifying the maximum pressure for the day 4 expected [987] but found [982],
	Verifying the maximum wind speed displayed in ui for the day 5 expected [7] but found [6]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at Page_Objects.EnterCityName_Objects.verifyWeatherForeCastForAllDays(EnterCityName_Objects.java:183)
	at testcases.EnterCItyName_Testcases.Login_process(EnterCItyName_Testcases.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_process -->
      </class> <!-- testcases.EnterCItyName_Testcases -->
      <class name="testcases.Browser_URL_Launch">
        <test-method status="PASS" signature="Browser_Launch(java.lang.String)[pri:0, instance:testcases.Browser_URL_Launch@cc285f4]" name="Browser_Launch" duration-ms="8927" started-at="2019-04-03T13:15:33Z" finished-at="2019-04-03T13:15:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Browser_Launch -->
        <test-method status="PASS" signature="urllaunch(java.lang.String)[pri:0, instance:testcases.Browser_URL_Launch@cc285f4]" name="urllaunch" duration-ms="12412" started-at="2019-04-03T13:15:42Z" data-provider="url_launch" depends-on-methods="testcases.Browser_URL_Launch.Browser_Launch" finished-at="2019-04-03T13:15:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://localhost:3000/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- urllaunch -->
      </class> <!-- testcases.Browser_URL_Launch -->
    </test> <!-- My test -->
  </suite> <!-- Suite1 -->
</testng-results>
